"""add train tables

Revision ID: 328137c8dae4
Revises: 23b1ec8a999a
Create Date: 2026-04-09 06:06:42.960640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '328137c8dae4'
down_revision: Union[str, None] = '23b1ec8a999a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('train_type', sa.String(length=20), nullable=False),
    sa.Column('source_station_code', sa.String(length=10), nullable=False),
    sa.Column('destination_station_code', sa.String(length=10), nullable=False),
    sa.Column('runs_on_days', sa.String(length=7), nullable=False),
    sa.Column('total_distance_km', sa.Integer(), nullable=True),
    sa.Column('has_pantry', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['destination_station_code'], ['stations.code'], ),
    sa.ForeignKeyConstraint(['source_station_code'], ['stations.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trains_destination_station_code'), 'trains', ['destination_station_code'], unique=False)
    op.create_index(op.f('ix_trains_number'), 'trains', ['number'], unique=True)
    op.create_index(op.f('ix_trains_source_station_code'), 'trains', ['source_station_code'], unique=False)
    op.create_table('train_schedule_stops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('train_id', sa.Uuid(), nullable=False),
    sa.Column('station_code', sa.String(length=10), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('departure_time', sa.Time(), nullable=True),
    sa.Column('halt_minutes', sa.Integer(), nullable=False),
    sa.Column('distance_from_source_km', sa.Integer(), nullable=False),
    sa.Column('day_offset', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['station_code'], ['stations.code'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_id', 'station_code', name='uq_train_station'),
    sa.UniqueConstraint('train_id', 'stop_sequence', name='uq_train_stop_seq')
    )
    op.create_index(op.f('ix_train_schedule_stops_train_id'), 'train_schedule_stops', ['train_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_train_schedule_stops_train_id'), table_name='train_schedule_stops')
    op.drop_table('train_schedule_stops')
    op.drop_index(op.f('ix_trains_source_station_code'), table_name='trains')
    op.drop_index(op.f('ix_trains_number'), table_name='trains')
    op.drop_index(op.f('ix_trains_destination_station_code'), table_name='trains')
    op.drop_table('trains')
    # ### end Alembic commands ###
