"""add chart and booking tables

Revision ID: 3821e4534133
Revises: 779fab6f5393
Create Date: 2026-04-09 06:12:25.634977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3821e4534133'
down_revision: Union[str, None] = '779fab6f5393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pnr_number', sa.String(length=10), nullable=False),
    sa.Column('train_id', sa.Uuid(), nullable=False),
    sa.Column('journey_date', sa.Date(), nullable=False),
    sa.Column('from_station_code', sa.String(length=10), nullable=False),
    sa.Column('to_station_code', sa.String(length=10), nullable=False),
    sa.Column('class_type', sa.String(length=5), nullable=False),
    sa.Column('quota', sa.String(length=5), nullable=False),
    sa.Column('booking_status', sa.String(length=20), nullable=False),
    sa.Column('total_fare_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=15), nullable=False),
    sa.Column('booked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_pnr_number'), 'bookings', ['pnr_number'], unique=True)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('reservation_charts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('train_id', sa.Uuid(), nullable=False),
    sa.Column('journey_date', sa.Date(), nullable=False),
    sa.Column('chart_sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('prepared_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_charts_train_id'), 'reservation_charts', ['train_id'], unique=False)
    op.create_table('booking_passengers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('passenger_name', sa.String(length=150), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('berth_preference', sa.String(length=10), nullable=True),
    sa.Column('current_status', sa.String(length=20), nullable=False),
    sa.Column('coach_label', sa.String(length=10), nullable=True),
    sa.Column('seat_number', sa.Integer(), nullable=True),
    sa.Column('berth_type', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_passengers_booking_id'), 'booking_passengers', ['booking_id'], unique=False)
    op.create_table('chart_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chart_id', sa.Uuid(), nullable=False),
    sa.Column('coach_label', sa.String(length=10), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('berth_type', sa.String(length=12), nullable=False),
    sa.Column('passenger_name', sa.String(length=150), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('from_station_code', sa.String(length=10), nullable=False),
    sa.Column('to_station_code', sa.String(length=10), nullable=False),
    sa.Column('booking_status', sa.String(length=20), nullable=False),
    sa.Column('pnr_number', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['reservation_charts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_entries_chart_id'), 'chart_entries', ['chart_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chart_entries_chart_id'), table_name='chart_entries')
    op.drop_table('chart_entries')
    op.drop_index(op.f('ix_booking_passengers_booking_id'), table_name='booking_passengers')
    op.drop_table('booking_passengers')
    op.drop_index(op.f('ix_reservation_charts_train_id'), table_name='reservation_charts')
    op.drop_table('reservation_charts')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_pnr_number'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
