"""add coach seat and seat_map tables

Revision ID: 779fab6f5393
Revises: 328137c8dae4
Create Date: 2026-04-09 06:09:26.201998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '779fab6f5393'
down_revision: Union[str, None] = '328137c8dae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train_coaches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('train_id', sa.Uuid(), nullable=False),
    sa.Column('coach_label', sa.String(length=10), nullable=False),
    sa.Column('class_type', sa.String(length=5), nullable=False),
    sa.Column('total_berths', sa.Integer(), nullable=False),
    sa.Column('coach_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_coaches_train_id'), 'train_coaches', ['train_id'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('train_coach_id', sa.Uuid(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('berth_type', sa.String(length=12), nullable=False),
    sa.Column('compartment_number', sa.Integer(), nullable=False),
    sa.Column('is_accessible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['train_coach_id'], ['train_coaches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_coach_id', 'seat_number', name='uq_coach_seat')
    )
    op.create_index(op.f('ix_seats_train_coach_id'), 'seats', ['train_coach_id'], unique=False)
    op.create_table('seat_map',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seat_id', sa.Uuid(), nullable=False),
    sa.Column('train_id', sa.Uuid(), nullable=False),
    sa.Column('journey_date', sa.Date(), nullable=False),
    sa.Column('boarding_stop_seq', sa.Integer(), nullable=False),
    sa.Column('deboarding_stop_seq', sa.Integer(), nullable=False),
    sa.Column('boarding_station_code', sa.String(length=10), nullable=False),
    sa.Column('deboarding_station_code', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('passenger_name', sa.String(length=150), nullable=True),
    sa.Column('pnr_number', sa.String(length=10), nullable=True),
    sa.Column('coach_label', sa.String(length=10), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('berth_type', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seat_map_seat_id'), 'seat_map', ['seat_id'], unique=False)
    op.create_index('ix_seat_map_vacancy_lookup', 'seat_map', ['train_id', 'journey_date', 'boarding_stop_seq', 'deboarding_stop_seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_seat_map_vacancy_lookup', table_name='seat_map')
    op.drop_index(op.f('ix_seat_map_seat_id'), table_name='seat_map')
    op.drop_table('seat_map')
    op.drop_index(op.f('ix_seats_train_coach_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_train_coaches_train_id'), table_name='train_coaches')
    op.drop_table('train_coaches')
    # ### end Alembic commands ###
